### PR TITLE
fix absolute start error

### PR DESCRIPTION
**Pull request by nadongguri**
Latest master branch occurs error when running "absolute start".
It is because of not existing database folder so handled it.

### CODE REVIEW

**Comment by nadongguri** [comment]
One thing I'm worrying about is the code mkdir -p in gulp file. Will it be better do it in absolute script file?

**Comment by romandev** [comment]
@nadongguri Thank you for this patch.

If you don't mind, let's use a easier way.
1. Make database directory.
2. Put just .gitkeep file (its content should be empty)
3. Then, there is no code like mkdir -p blah blah in gulp file.

**Comment by nadongguri** [comment]
Okay. I appreciate your kindness guide. :-)

**Comment by nadongguri** [comment]
Made it out!

**Comment by Wuseok** [comment]
oh... I'm late.

**Pull request merged**
